#!/usr/bin/env python3
"""Assemble the ordered section sources into GitHub-native articles."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SECTIONS = ROOT / "sections"
EDITIONS = (
    ("README.md", ROOT / "BLOG.md"),
    ("README.zh.md", ROOT / "BLOG.zh.md"),
)


def section_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8").strip()
    section_dir = path.parent.relative_to(ROOT).as_posix()
    text = re.sub(r"\]\(assets/", f"]({section_dir}/assets/", text)
    text = text.replace("](../../experiments/", "](experiments/")
    text = text.replace('src="assets/', f'src="{section_dir}/assets/')
    return text


def build(source_name: str) -> str:
    section_files = sorted(SECTIONS.glob(f"*/{source_name}"))
    body = [
        "<!-- GENERATED by scripts/build_blog.py; edit sections/* sources. -->",
        "",
    ]
    for index, path in enumerate(section_files):
        if index:
            body.extend(["", "---", ""])
        body.append(section_text(path))
    return "\n".join(body).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    for source_name, output in EDITIONS:
        generated = build(source_name)
        if args.check:
            current = output.read_text(encoding="utf-8") if output.exists() else ""
            if current != generated:
                stale.append(output.name)
        else:
            output.write_text(generated, encoding="utf-8")

    if stale:
        raise SystemExit(f"{', '.join(stale)} stale; run python scripts/build_blog.py")


if __name__ == "__main__":
    main()
