#!/usr/bin/env python3
"""Assemble the ordered section READMEs into one GitHub-native article."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SECTIONS = ROOT / "sections"
OUTPUT = ROOT / "BLOG.md"


def section_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8").strip()
    section_dir = path.parent.relative_to(ROOT).as_posix()
    text = re.sub(r"\]\(assets/", f"]({section_dir}/assets/", text)
    text = text.replace('src="assets/', f'src="{section_dir}/assets/')
    return text


def build() -> str:
    section_files = sorted(SECTIONS.glob("*/README.md"))
    body = [
        "<!-- GENERATED by scripts/build_blog.py; edit sections/*/README.md. -->",
        "",
        "[Back to the modular repository index](README.md)",
        "",
    ]
    for index, path in enumerate(section_files):
        if index:
            body.extend(["", "---", ""])
        body.append(section_text(path))
    return "\n".join(body).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = build()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            raise SystemExit("BLOG.md is stale; run python scripts/build_blog.py")
        return
    OUTPUT.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
